 * Serving Flask app 'yolo_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
YOLOv5 ðŸš€ 4efdefb torch 1.10.0+cu102 CPU

Fusing layers... 
/home/ec2-user/.local/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 224 layers, 7320913 parameters, 0 gradients, 17.2 GFLOPs
127.0.0.1 - - [25/Nov/2021 03:13:51] "POST /calorie HTTP/1.1" 200 -
127.0.0.1 - - [25/Nov/2021 03:13:51] "POST /calorie HTTP/1.1" 200 -
 * Serving Flask app 'yolo_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "yolo_server.py", line 40, in <module>
    app.run()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 959, in inner
    fd=fd,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 783, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/usr/lib64/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app 'yolo_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "yolo_server.py", line 40, in <module>
    app.run()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 959, in inner
    fd=fd,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 783, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/usr/lib64/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
YOLOv5 ðŸš€ 4efdefb torch 1.10.0+cu102 CPU

Fusing layers... 
Model Summary: 224 layers, 7320913 parameters, 0 gradients, 17.2 GFLOPs
127.0.0.1 - - [26/Nov/2021 23:20:33] "POST /calorie HTTP/1.1" 200 -
127.0.0.1 - - [26/Nov/2021 23:20:33] "POST /calorie HTTP/1.1" 200 -
YOLOv5 ðŸš€ 4efdefb torch 1.10.0+cu102 CPU

Fusing layers... 
Model Summary: 224 layers, 7320913 parameters, 0 gradients, 17.2 GFLOPs
127.0.0.1 - - [30/Nov/2021 19:22:25] "POST /calorie HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2021 19:22:25] "POST /calorie HTTP/1.1" 200 -
YOLOv5 ðŸš€ 4efdefb torch 1.10.0+cu102 CPU

Fusing layers... 
Model Summary: 224 layers, 7320913 parameters, 0 gradients, 17.2 GFLOPs
127.0.0.1 - - [30/Nov/2021 19:31:28] "POST /calorie HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2021 19:31:28] "POST /calorie HTTP/1.1" 200 -
Downloading https://ultralytics.com/assets/Arial.ttf to /home/ec2-user/.config/Ultralytics/Arial.ttf...
 * Serving Flask app 'yolo_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "yolo_server.py", line 40, in <module>
    app.run()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 959, in inner
    fd=fd,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 783, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/usr/lib64/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app 'yolo_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "yolo_server.py", line 40, in <module>
    app.run()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 959, in inner
    fd=fd,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 783, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/ec2-user/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/usr/lib64/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app 'yolo_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
